server.port=8080

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/catalog/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/admin/**


springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/api/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Catalog Service
springdoc.swagger-ui.urls[1].url=/api/catalog/v3/api-docs

springdoc.swagger-ui.urls[2].name=Order Service
springdoc.swagger-ui.urls[2].url=/api/orders/v3/api-docs

springdoc.swagger-ui.urls[3].name=Admin Service
springdoc.swagger-ui.urls[3].url=/api/admin/v3/api-docs

spring.cloud.gateway.routes[4].id=auth-docs
spring.cloud.gateway.routes[4].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/v3/api-docs/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/auth/v3/api-docs/(?<segment>.*),/v3/api-docs/${segment}

spring.cloud.gateway.routes[5].id=catalog-docs
spring.cloud.gateway.routes[5].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/catalog/v3/api-docs/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/api/catalog/v3/api-docs/(?<segment>.*),/v3/api-docs/${segment}

spring.cloud.gateway.routes[6].id=order-docs
spring.cloud.gateway.routes[6].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/orders/v3/api-docs/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/api/orders/v3/api-docs/(?<segment>.*),/v3/api-docs/${segment}

spring.cloud.gateway.routes[7].id=admin-docs
spring.cloud.gateway.routes[7].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/admin/v3/api-docs/**
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/api/admin/v3/api-docs/(?<segment>.*),/v3/api-docs/${segment}
